ERROR - 2022-10-24 02:21:07 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\laragon\www\tabel-adv\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\laragon\www\tabel-adv\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 C:\laragon\www\tabel-adv\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\tabel-adv\vendor\codeigniter4\framework\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\tabel-adv\app\Controllers\Home.php(17): CodeIgniter\Database\BaseConnection->query('SELECT * FROM u...')
#4 C:\laragon\www\tabel-adv\vendor\codeigniter4\framework\system\CodeIgniter.php(902): App\Controllers\Home->index()
#5 C:\laragon\www\tabel-adv\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 C:\laragon\www\tabel-adv\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\laragon\www\tabel-adv\public\index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\laragon\www\tabel-adv\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\laragon\www\tabel-adv\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\tabel-adv\vendor\codeigniter4\framework\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\tabel-adv\app\Controllers\Home.php(17): CodeIgniter\Database\BaseConnection->query('SELECT * FROM u...')
#3 C:\laragon\www\tabel-adv\vendor\codeigniter4\framework\system\CodeIgniter.php(902): App\Controllers\Home->index()
#4 C:\laragon\www\tabel-adv\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\laragon\www\tabel-adv\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\laragon\www\tabel-adv\public\index.php(67): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-10-24 02:21:07 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\Home.php(17): CodeIgniter\Database\BaseConnection->query('SELECT * FROM user ORDER BY user_id ASC')
 3 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\Home->index()
 4 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 5 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-10-24 02:25:38 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\laragon\www\tabel-adv\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\laragon\www\tabel-adv\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 C:\laragon\www\tabel-adv\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\tabel-adv\vendor\codeigniter4\framework\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\tabel-adv\app\Controllers\Home.php(17): CodeIgniter\Database\BaseConnection->query('SELECT * FROM u...')
#4 C:\laragon\www\tabel-adv\vendor\codeigniter4\framework\system\CodeIgniter.php(902): App\Controllers\Home->index()
#5 C:\laragon\www\tabel-adv\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 C:\laragon\www\tabel-adv\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\laragon\www\tabel-adv\public\index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\laragon\www\tabel-adv\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\laragon\www\tabel-adv\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\tabel-adv\vendor\codeigniter4\framework\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\tabel-adv\app\Controllers\Home.php(17): CodeIgniter\Database\BaseConnection->query('SELECT * FROM u...')
#3 C:\laragon\www\tabel-adv\vendor\codeigniter4\framework\system\CodeIgniter.php(902): App\Controllers\Home->index()
#4 C:\laragon\www\tabel-adv\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\laragon\www\tabel-adv\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\laragon\www\tabel-adv\public\index.php(67): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-10-24 02:25:38 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\Home.php(17): CodeIgniter\Database\BaseConnection->query('SELECT * FROM user ORDER BY user_id ASC')
 3 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\Home->index()
 4 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 5 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-10-24 02:26:10 --> mysqli_sql_exception: Table 'tabel-adv.tables' doesn't exist in C:\laragon\www\tabel-adv\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\laragon\www\tabel-adv\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT data1 FR...', 0)
#1 C:\laragon\www\tabel-adv\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT data1 FR...')
#2 C:\laragon\www\tabel-adv\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT data1 FR...')
#3 C:\laragon\www\tabel-adv\app\Views\html.php(633): CodeIgniter\Database\BaseConnection->query('SELECT data1 FR...')
#4 C:\laragon\www\tabel-adv\vendor\codeigniter4\framework\system\View\View.php(213): include('C:\\laragon\\www\\...')
#5 C:\laragon\www\tabel-adv\vendor\codeigniter4\framework\system\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 C:\laragon\www\tabel-adv\vendor\codeigniter4\framework\system\Common.php(1142): CodeIgniter\View\View->render('html', Array, true)
#7 C:\laragon\www\tabel-adv\app\Controllers\Home.php(79): view('html', Array)
#8 C:\laragon\www\tabel-adv\vendor\codeigniter4\framework\system\CodeIgniter.php(902): App\Controllers\Home->html()
#9 C:\laragon\www\tabel-adv\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 C:\laragon\www\tabel-adv\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\tabel-adv\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2022-10-24 02:26:10 --> Table 'tabel-adv.tables' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('SELECT data1 FROM tables GROUP BY data1', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT data1 FROM tables GROUP BY data1')
 3 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT data1 FROM tables GROUP BY data1')
 4 APPPATH\Views\html.php(633): CodeIgniter\Database\BaseConnection->query('SELECT data1 FROM tables GROUP BY data1')
 5 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\html.php')
 6 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 7 SYSTEMPATH\Common.php(1142): CodeIgniter\View\View->render('html', [], true)
 8 APPPATH\Controllers\Home.php(79): view('html', [...])
 9 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\Home->html()
10 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
11 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
